### ISSUE TITLE
El carrito del navbar no muestra la cantidad de productos cargados en todas las paginas

### ISSUE THREAD

**Issue by emiarias** [EduRossB/ProyectoModulo2#1]
La cantidad de productos del carrito cambia dependiendo en la pagina que estamos

![image](https://user-images.githubusercontent.com/18445151/191388138-3665dfaf-fde0-4f88-8741-d536dd93b0a9.png)

![image](https://user-images.githubusercontent.com/18445151/191388162-4e16057e-3dcb-4988-a046-c5b7fb2cb7fe.png)

![image](https://user-images.githubusercontent.com/18445151/191388192-9d0ce663-c083-4813-a278-c2775ea3aa00.png)

![image](https://user-images.githubusercontent.com/18445151/191388221-63745888-0452-40ed-adb5-6168dd03b70b.png)

**Comment by NicolasGalia** [comment]
solucionado! 👌👌
