### ISSUE TITLE
Al loguear el usuario indicar que inicio sesion

### ISSUE THREAD

**Issue by emiarias** [EduRossB/ProyectoModulo2#2]
Mostrar el nombre de usuario o algun mensaje para que el usuario sepa que inicio sesion, ademas agregar la opcion para cerrar sesion

![image](https://user-images.githubusercontent.com/18445151/191388725-22c6a1b5-52d6-4a79-84ea-722182a2225f.png)

**Comment by mattelgrandexx** [comment]
Solucionado, ahora aparece el nombre del usuario al tener la sesion abierta en todas las paginas.
